gpioList = {}

RPI_GPIO_CONFIGURATION = [
    {'name': 'GPIO2_I2C_SDA',           'type': 'pi', 'physical': '3',  'wPi': '8', 'BCM': '2',  'mode': 'alt0', 'value': '0'},
    {'name': 'GPIO3_I2C_SCL',           'type': 'pi', 'physical': '5',  'wPi': '9', 'BCM': '3',  'mode': 'alt0', 'value': '0'},
    {'name': 'GPIO4_EXPAND_RST2',       'type': 'pi', 'physical': '7',  'wPi': '7', 'BCM': '4',  'mode': 'out',  'value': '1'},
    {'name': 'GPIO14_NO_USE',           'type': 'pi', 'physical': '8',  'wPi': '15','BCM': '14', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO15_NO_USE',           'type': 'pi', 'physical': '10', 'wPi': '16','BCM': '15', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO17_EXPAND_RST1',      'type': 'pi', 'physical': '11', 'wPi': '0', 'BCM': '17', 'mode': 'out',  'value': '1'},
    {'name': 'GPIO18_AUDIO_PCM_CLK',    'type': 'pi', 'physical': '12', 'wPi': '1', 'BCM': '18', 'mode': 'alt0',  'value': '0'},
    {'name': 'GPIO27_DUT_INT1',         'type': 'pi', 'physical': '13', 'wPi': '2', 'BCM': '27', 'mode': 'out',   'value': '0'},
    {'name': 'GPIO22_DUT_INT2',         'type': 'pi', 'physical': '15', 'wPi': '3', 'BCM': '22', 'mode': 'out',   'value': '0'},
    {'name': 'GPIO23_SW_SIGNAL_RESERVE','type': 'pi', 'physical': '16', 'wPi': '4', 'BCM': '23', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO24_AUDIO_CMX_RST',    'type': 'pi', 'physical': '18', 'wPi': '5', 'BCM': '24', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO10_NO_USE',           'type': 'pi', 'physical': '19', 'wPi': '12','BCM': '10', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO9_NO_USE',            'type': 'pi', 'physical': '21', 'wPi': '13','BCM': '9',  'mode': 'in',   'value': '0'},
    {'name': 'GPIO25_AUDIO_CMX_IRQN',   'type': 'pi', 'physical': '22', 'wPi': '6', 'BCM': '25', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO11_NO_USE',           'type': 'pi', 'physical': '23', 'wPi': '14','BCM': '11', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO8_NO_USE',            'type': 'pi', 'physical': '24', 'wPi': '10','BCM': '8',  'mode': 'in',   'value': '0'},
    {'name': 'GPIO7_NO_USE',            'type': 'pi', 'physical': '26', 'wPi': '11','BCM': '7',  'mode': 'in',   'value': '0'},
    {'name': 'GPIO0_I2C_SDA_EPROM',     'type': 'pi', 'physical': '27', 'wPi': '30','BCM': '0',  'mode': 'alt0', 'value': '0'},
    {'name': 'GPIO1_I2C_SCL_EPROM',     'type': 'pi', 'physical': '28', 'wPi': '31','BCM': '1',  'mode': 'alt0', 'value': '0'},
    {'name': 'GPIO5_NO_USE',            'type': 'pi', 'physical': '29', 'wPi': '21','BCM': '5',  'mode': 'in',   'value': '0'},
    {'name': 'GPIO6_NO_USE',            'type': 'pi', 'physical': '31', 'wPi': '22','BCM': '6',  'mode': 'in',   'value': '0'},
    {'name': 'GPIO12_NO_USE',           'type': 'pi', 'physical': '32', 'wPi': '26','BCM': '12', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO13_NO_USE',           'type': 'pi', 'physical': '33', 'wPi': '23','BCM': '13', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO19_AUDIO_PCM_FS',     'type': 'pi', 'physical': '35', 'wPi': '24','BCM': '19', 'mode': 'alt0',   'value': '0'},
    {'name': 'GPIO16_NO_USE',           'type': 'pi', 'physical': '36', 'wPi': '27','BCM': '16', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO26_NO_USE',           'type': 'pi', 'physical': '37', 'wPi': '25','BCM': '26', 'mode': 'in',   'value': '0'},
    {'name': 'GPIO20_AUDIO_PCM_DIN',    'type': 'pi', 'physical': '38', 'wPi': '28','BCM': '20', 'mode': 'alt0',   'value': '0'},
    {'name': 'GPIO21_AUDIO_PCM_DOUT',   'type': 'pi', 'physical': '40', 'wPi': '29','BCM': '21', 'mode': 'in',   'value': '0'},
]